apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: deall
  name: deall
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: deall
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: deall
    spec:
      containers:
        - env:
            - name: JWT_EXPIRED
              value: 1h
            - name: JWT_SECRET
              value: adadech
            - name: PORT
              value: "3000"
            - name: REFRESH-TOKEN_HOST
              value: refresh-token
            - name: REFRESH-TOKEN_PORT
              value: "3001"
            - name: USER_HOST
              value: user
            - name: USER_PORT
              value: "3002"
          image: deall:2.0
          name: deall
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
